# Generated by Django 4.2.3 on 2023-07-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dicionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=50)),
                ('pronuncia', models.CharField(blank=True, max_length=50, null=True)),
                ('rima', models.CharField(blank=True, max_length=20, null=True)),
                ('silabas', models.IntegerField()),
            ],
        ),
    ]
